### ISSUE TITLE
[Cedar Doc Issue] Doc updates for 4.0.0

### ISSUE THREAD

**Issue by khieta** [cedar-policy/cedar-docs#125]
Creating this issue to track the progress of doc updates for the newly released v4.0.0.

- [x] Replace uses of "human", "human-readable" with "Cedar" https://github.com/cedar-policy/cedar/pull/1114
- [x] Reserve `__cedar` identifier for internal use [rfc#52](https://github.com/cedar-policy/rfcs/blob/main/text/0052-reserved-namespaces.md)
- [x] Remove unspecified entities [rfc#55](https://github.com/cedar-policy/rfcs/blob/main/text/0055-remove-unspecified.md)
- [x] Disallow shadowing definitions in the empty namespace [rfc#70](https://github.com/cedar-policy/rfcs/blob/main/text/0070-disallow-empty-namespace-shadowing.md)
- [x] Allow `EntityOrCommon` field in JSON schema https://github.com/cedar-policy/cedar/pull/1060
- [x] Disallow `Bool`, `Boolean`, `Entity`, `Extension`, `Long`, `Record`, `Set`, and `String` as common type names in schemas https://github.com/cedar-policy/cedar/pull/1150
